name: Weekly Canary

on:
    schedule:
        - cron: '0 0 * * Mon'

jobs:
  weekly-canary-build:
    strategy:
        matrix:
            rust-channel: [stable, beta, nightly]
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        uses: taiki-e/install-action@v2
        with:
          tool: mdslides@0.3,mdbook@0.4,mdbook-mermaid@0.12,flip-link@0.1.7

      - name: Install targets
        run: |
          rustup target add thumbv7em-none-eabihf
          rustup component add rust-src
          rustup component add rustfmt

      - name: Update and set default Rust
        run: |
          rustup update ${{ matrix.rust-channel }}
          rustup default ${{ matrix.rust-channel }}

      - name: Find slug name
        run: |
          slug=$(./describe.sh "${GITHUB_REF}")
          echo "Building with slug '${slug}'"
          echo "slug=${slug}" >> "${GITHUB_ENV}"

      - name: Build and test
        env: # Or as an environment variable
          HIDDEN_MESSAGE: ${{ secrets.HIDDEN_MESSAGE }}
        run: |
          ./build.sh "./rust-exercises-${{ env.slug }}"